# 1단계: 빌드 스테이지
FROM gradle:8.5-jdk17 AS builder

# 작업 디렉토리 설정
WORKDIR /app

# Gradle 캐시 최적화를 위한 설정
COPY build.gradle.kts settings.gradle.kts ./
COPY gradle ./gradle
COPY src ./src

# 빌드 시점 환경변수 인자 정의
ARG SPRING_PROFILES_ACTIVE
ARG DEV_DB_NAME
ARG DEV_DB_USERNAME
ARG DEV_DB_PASSWORD
ARG DEV_DB_HOST
ARG DEV_DB_PORT
ARG JWT_ACCESS_TOKEN_EXPIRATION
ARG JWT_REFRESH_TOKEN_EXPIRATION
ARG JWT_REFRESH_COOKIE_NAME
ARG JWT_REFRESH_COOKIE_MAX_AGE
ARG JWT_SECRET
ARG FRONTEND_IS_LOCAL
ARG COOKIE_DEV_DOMAIN
ARG DEV_FRONTEND_REDIRECT_URI
ARG FORTUNE_SERVICE_ERROR_MESSAGE
ARG FORTUNE_SERVICE_URI
ARG AI_COMMENT_SERVICE_URL
ARG AI_COMMENT_DEFAULT_TYPE
ARG AI_BADGE_SERVICE_URL
ARG RANKING_SNAPSHOT_DURATION_MINUTES
ARG DEFAULT_PROFILE_IMAGE_PU_URL
ARG DEFAULT_PROFILE_IMAGE_MATI_URL
ARG DEFAULT_BADGE_IMAGE_URL
ARG OAUTH_ALLOWED_PROVIDERS
ARG KAKAO_AUTHORIZATION_GRANT_TYPE
ARG KAKAO_CLIENT_AUTHENTICATION_METHOD
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_NAME
ARG KAKAO_CLIENT_SECRET
ARG KAKAO_REDIRECT_URI
ARG KAKAO_SCOPE
ARG KAKAO_AUTHORIZATION_URI
ARG KAKAO_TOKEN_URI
ARG KAKAO_USER_INFO_URI
ARG KAKAO_USER_NAME_ATTRIBUTE
ARG AWS_REGION
ARG AWS_CREDENTIALS_ACCESS_KEY
ARG AWS_CREDENTIALS_SECRET_KEY
ARG AWS_S3_BUCKET_NAME
ARG AWS_S3_EXPIRATION_PUT_MINUTES
ARG AWS_S3_MAX_REQUEST_COUNT

# 환경변수 설정
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
ENV DEV_DB_NAME=$DEV_DB_NAME
ENV DEV_DB_USERNAME=$DEV_DB_USERNAME
ENV DEV_DB_PASSWORD=$DEV_DB_PASSWORD
ENV DEV_DB_HOST=$DEV_DB_HOST
ENV DEV_DB_PORT=$DEV_DB_PORT
ENV JWT_ACCESS_TOKEN_EXPIRATION=$JWT_ACCESS_TOKEN_EXPIRATION
ENV JWT_REFRESH_TOKEN_EXPIRATION=$JWT_REFRESH_TOKEN_EXPIRATION
ENV JWT_REFRESH_COOKIE_NAME=$JWT_REFRESH_COOKIE_NAME
ENV JWT_REFRESH_COOKIE_MAX_AGE=$JWT_REFRESH_COOKIE_MAX_AGE
ENV JWT_SECRET=$JWT_SECRET
ENV FRONTEND_IS_LOCAL=$FRONTEND_IS_LOCAL
ENV COOKIE_DEV_DOMAIN=$COOKIE_DEV_DOMAIN
ENV DEV_FRONTEND_REDIRECT_URI=$DEV_FRONTEND_REDIRECT_URI
ENV FORTUNE_SERVICE_ERROR_MESSAGE=$FORTUNE_SERVICE_ERROR_MESSAGE
ENV FORTUNE_SERVICE_URI=$FORTUNE_SERVICE_URI
ENV AI_COMMENT_SERVICE_URL=$AI_COMMENT_SERVICE_URL
ENV AI_COMMENT_DEFAULT_TYPE=$AI_COMMENT_DEFAULT_TYPE
ENV AI_BADGE_SERVICE_URL=$AI_BADGE_SERVICE_URL
ENV RANKING_SNAPSHOT_DURATION_MINUTES=$RANKING_SNAPSHOT_DURATION_MINUTES
ENV DEFAULT_PROFILE_IMAGE_PU_URL=$DEFAULT_PROFILE_IMAGE_PU_URL
ENV DEFAULT_PROFILE_IMAGE_MATI_URL=$DEFAULT_PROFILE_IMAGE_MATI_URL
ENV DEFAULT_BADGE_IMAGE_URL=$DEFAULT_BADGE_IMAGE_URL
ENV OAUTH_ALLOWED_PROVIDERS=$OAUTH_ALLOWED_PROVIDERS
ENV KAKAO_AUTHORIZATION_GRANT_TYPE=$KAKAO_AUTHORIZATION_GRANT_TYPE
ENV KAKAO_CLIENT_AUTHENTICATION_METHOD=$KAKAO_CLIENT_AUTHENTICATION_METHOD
ENV KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
ENV KAKAO_CLIENT_NAME=$KAKAO_CLIENT_NAME
ENV KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET
ENV KAKAO_REDIRECT_URI=$KAKAO_REDIRECT_URI
ENV KAKAO_SCOPE=$KAKAO_SCOPE
ENV KAKAO_AUTHORIZATION_URI=$KAKAO_AUTHORIZATION_URI
ENV KAKAO_TOKEN_URI=$KAKAO_TOKEN_URI
ENV KAKAO_USER_INFO_URI=$KAKAO_USER_INFO_URI
ENV KAKAO_USER_NAME_ATTRIBUTE=$KAKAO_USER_NAME_ATTRIBUTE
ENV AWS_REGION=$AWS_REGION
ENV AWS_CREDENTIALS_ACCESS_KEY=$AWS_CREDENTIALS_ACCESS_KEY
ENV AWS_CREDENTIALS_SECRET_KEY=$AWS_CREDENTIALS_SECRET_KEY
ENV AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME
ENV AWS_S3_EXPIRATION_PUT_MINUTES=$AWS_S3_EXPIRATION_PUT_MINUTES
ENV AWS_S3_MAX_REQUEST_COUNT=$AWS_S3_MAX_REQUEST_COUNT

# Gradle 빌드 실행 (테스트 제외)
RUN gradle build -x test

# 2단계: 실행용 스테이지
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# 빌드된 JAR 파일 복사
COPY --from=builder /app/build/libs/*.jar app.jar

# 포트 노출
EXPOSE 8080

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "app.jar"]
